const gare2025 = [
    {
        "anno": 2025,
        "gara": "Australia",
        "piloti": [
            {
                "nome": "Lando Norris",
                "scuderia": "McLaren",
                "q1": "1:15.912",
                "q2": "1:15.415",
                "q3": "1:15.096",
                "posizioneQualifica": 1,
                "posizioneFinale": 1,
                "giroVeloce": true,
                "pilotaDelGiorno": true,
                "dnf": false
            },
            {
                "nome": "Oscar Piastri",
                "scuderia": "McLaren",
                "q1": "1:16.062",
                "q2": "1:15.468",
                "q3": "1:15.180",
                "posizioneQualifica": 2,
                "posizioneFinale": 9,
                "giroVeloce": false,
                "pilotaDelGiorno": false,
                "dnf": false
            },
            {
                "nome": "Max Verstappen",
                "scuderia": "Red Bull",
                "q1": "1:16.018",
                "q2": "1:15.565",
                "q3": "1:15.481",
                "posizioneQualifica": 3,
                "posizioneFinale": 2,
                "giroVeloce": false,
                "pilotaDelGiorno": false,
                "dnf": false
            },
            {
                "nome": "Yuki Tsunoda",
                "scuderia": "Racing Bulls",
                "q1": "1:16.225",
                "q2": "1:16.009",
                "q3": "1:15.670",
                "posizioneQualifica": 5,
                "posizioneFinale": 12,
                "giroVeloce": false,
                "pilotaDelGiorno": false,
                "dnf": false
            },
            {
                "nome": "Charles Leclerc",
                "scuderia": "Ferrari",
                "q1": "1:16.029",
                "q2": "1:15.827",
                "q3": "1:15.755",
                "posizioneQualifica": 7,
                "posizioneFinale": 8,
                "giroVeloce": false,
                "pilotaDelGiorno": false,
                "dnf": false
            },
            {
                "nome": "Lewis Hamilton",
                "scuderia": "Ferrari",
                "q1": "1:16.213",
                "q2": "1:15.919",
                "q3": "1:15.973",
                "posizioneQualifica": 8,
                "posizioneFinale": 10,
                "giroVeloce": false,
                "pilotaDelGiorno": false,
                "dnf": false
            },
            {
                "nome": "George Russell",
                "scuderia": "Mercedes",
                "q1": "1:15.971",
                "q2": "1:15.798",
                "q3": "1:15.546",
                "posizioneQualifica": 4,
                "posizioneFinale": 3,
                "giroVeloce": false,
                "pilotaDelGiorno": false,
                "dnf": false
            },
            {
                "nome": "Kimi Antonelli",
                "scuderia": "Mercedes",
                "q1": "1:16.525",
                "q2": "",
                "q3": "",
                "posizioneQualifica": 16,
                "posizioneFinale": 4,
                "giroVeloce": false,
                "pilotaDelGiorno": false,
                "dnf": false
            },
            {
                "nome": "Alexander Albon",
                "scuderia": "Williams",
                "q1": "1:16.245",
                "q2": "1:16.017",
                "q3": "1:15.738",
                "posizioneQualifica": 6,
                "posizioneFinale": 5,
                "giroVeloce": false,
                "pilotaDelGiorno": false,
                "dnf": false
            },
            {
                "nome": "Carlos Sainz",
                "scuderia": "Williams",
                "q1": "1:16.360",
                "q2": "1:15.931",
                "q3": "1:16.062",
                "posizioneQualifica": 10,
                "posizioneFinale": null,
                "giroVeloce": false,
                "pilotaDelGiorno": false,
                "dnf": true
            },
            {
                "nome": "Isack Hadjar",
                "scuderia": "Racing Bulls",
                "q1": "1:16.354",
                "q2": "1:16.175",
                "q3": "",
                "posizioneQualifica": 11,
                "posizioneFinale": null,
                "giroVeloce": false,
                "pilotaDelGiorno": false,
                "dnf": true
            },
            {
                "nome": "Liam Lawson",
                "scuderia": "Red Bull",
                "q1": "1:17.094",
                "q2": "",
                "q3": "",
                "posizioneQualifica": 18,
                "posizioneFinale": null,
                "giroVeloce": false,
                "pilotaDelGiorno": false,
                "dnf": true
            },
            {
                "nome": "Esteban Ocon",
                "scuderia": "Haas",
                "q1": "1:17.147",
                "q2": "",
                "q3": "",
                "posizioneQualifica": 19,
                "posizioneFinale": 13,
                "giroVeloce": false,
                "pilotaDelGiorno": false,
                "dnf": false
            },
            {
                "nome": "Oliver Bearman",
                "scuderia": "Haas",
                "q1": "1:17.147",
                "q2": "",
                "q3": "",
                "posizioneQualifica": null,
                "posizioneFinale": 14,
                "giroVeloce": false,
                "pilotaDelGiorno": false,
                "dnf": false
            },
            {
                "nome": "Niko Hulkenberg",
                "scuderia": "Sauber",
                "q1": "1:16.579",
                "q2": "",
                "q3": "",
                "posizioneQualifica": 17,
                "posizioneFinale": 7,
                "giroVeloce": false,
                "pilotaDelGiorno": false,
                "dnf": false
            },
            {
                "nome": "Gabriel Bortoleto",
                "scuderia": "Sauber",
                "q1": "1:16.516",
                "q2": "1:17.520",
                "q3": "",
                "posizioneQualifica": 15,
                "posizioneFinale": null,
                "giroVeloce": false,
                "pilotaDelGiorno": false,
                "dnf": true
            },
            {
                "nome": "Fernando Alonso",
                "scuderia": "Aston Martin",
                "q1": "1:16.288",
                "q2": "1:16.453",
                "q3": "",
                "posizioneQualifica": 12,
                "posizioneFinale": null,
                "giroVeloce": false,
                "pilotaDelGiorno": false,
                "dnf": true
            },
            {
                "nome": "Lance Stroll",
                "scuderia": "Aston Martin",
                "q1": "1:16.369",
                "q2": "1:16.483",
                "q3": "",
                "posizioneQualifica": 13,
                "posizioneFinale": 6,
                "giroVeloce": false,
                "pilotaDelGiorno": false,
                "dnf": false
            },
            {
                "nome": "Pierre Gasly",
                "scuderia": "Alpine",
                "q1": "1:16.328",
                "q2": "1:16.112",
                "q3": "1:15.980",
                "posizioneQualifica": 9,
                "posizioneFinale": 11,
                "giroVeloce": false,
                "pilotaDelGiorno": false,
                "dnf": false
            },
            {
                "nome": "Franco Colapinto",
                "scuderia": "Alpine",
                "q1": "1:16.863",
                "q2": "",
                "q3": "",
                "posizioneQualifica": null,
                "posizioneFinale": null,
                "giroVeloce": false,
                "pilotaDelGiorno": false,
                "dnf": false
            },
            {
                "nome": "Jack Doohan",
                "scuderia": "Alpine",
                "q1": "1:16.315",
                "q2": "1:16.863",
                "q3": "",
                "posizioneQualifica": 14,
                "posizioneFinale": null,
                "giroVeloce": false,
                "pilotaDelGiorno": false,
                "dnf": true
            },
        ]
    },
    {
        "anno": 2025,
        "gara": "Cina",
        "piloti": [
            {
                "nome": "Lando Norris",
                "scuderia": "McLaren",
                "q1": "1:30.983",
                "q2": "1:30.787",
                "q3": "1:30.793",
                "posizioneQualifica": 3,
                "posizioneFinale": 2,
                "giroVeloce": true,
                "pilotaDelGiorno": false,
                "dnf": false,
                "sprint": 8,
            },
            {
                "nome": "Oscar Piastri",
                "scuderia": "McLaren",
                "q1": "1:31.591",
                "q2": "1:31.200",
                "q3": "1:30.641",
                "posizioneQualifica": 1,
                "posizioneFinale": 1,
                "giroVeloce": false,
                "pilotaDelGiorno": false,
                "dnf": false,
                "sprint": 2,
            },
            {
                "nome": "Max Verstappen",
                "scuderia": "Red Bull",
                "q1": "1:31.424",
                "q2": "1:31.142",
                "q3": "1:30.817",
                "posizioneQualifica": 4,
                "posizioneFinale": 4,
                "giroVeloce": false,
                "pilotaDelGiorno": false,
                "dnf": false,
                "sprint": 3,
            },
            {
                "nome": "Yuki Tsunoda",
                "scuderia": "Racing Bulls",
                "q1": "1:31.238",
                "q2": "1:31.260",
                "q3": "1:31.638",
                "posizioneQualifica": 9,
                "posizioneFinale": 16,
                "giroVeloce": false,
                "pilotaDelGiorno": false,
                "dnf": false,
                "sprint": 6,
            },
            {
                "nome": "Charles Leclerc",
                "scuderia": "Ferrari",
                "q1": "1:31.579",
                "q2": "1:31.450",
                "q3": "1:31.021",
                "posizioneQualifica": 6,
                "posizioneFinale": null,
                "giroVeloce": false,
                "pilotaDelGiorno": false,
                "dnf": true,
                "sprint": 5,
            },
            {
                "nome": "Lewis Hamilton",
                "scuderia": "Ferrari",
                "q1": "1:31.690",
                "q2": "1:31.501",
                "q3": "1:30.927",
                "posizioneQualifica": 5,
                "posizioneFinale": null,
                "giroVeloce": false,
                "pilotaDelGiorno": false,
                "dnf": true,
                "sprint": 1,
            },
            {
                "nome": "George Russell",
                "scuderia": "Mercedes",
                "q1": "1:31.295",
                "q2": "1:31.307",
                "q3": "1:30.723",
                "posizioneQualifica": 2,
                "posizioneFinale": 3,
                "giroVeloce": false,
                "pilotaDelGiorno": false,
                "dnf": false,
                "sprint": 4,
            },
            {
                "nome": "Kimi Antonelli",
                "scuderia": "Mercedes",
                "q1": "1:31.676",
                "q2": "1:31.590",
                "q3": "1:31.103",
                "posizioneQualifica": 8,
                "posizioneFinale": 6,
                "giroVeloce": false,
                "pilotaDelGiorno": true,
                "dnf": false,
                "sprint": 7,
            },
            {
                "nome": "Alexander Albon",
                "scuderia": "Williams",
                "q1": "1:31.503",
                "q2": "1:31.595",
                "q3": "1:31.706",
                "posizioneQualifica": 10,
                "posizioneFinale": 7,
                "giroVeloce": false,
                "pilotaDelGiorno": false,
                "dnf": false,
                "sprint": 11,
            },
            {
                "nome": "Carlos Sainz",
                "scuderia": "Williams",
                "q1": "1:31.628",
                "q2": "1:31.840",
                "q3": "",
                "posizioneQualifica": 15,
                "posizioneFinale": 10,
                "giroVeloce": false,
                "pilotaDelGiorno": false,
                "dnf": false,
                "sprint": 17,
            },
            {
                "nome": "Isack Hadjar",
                "scuderia": "Racing Bulls",
                "q1": "1:31.162",
                "q2": "1:31.253",
                "q3": "1:31.079",
                "posizioneQualifica": 7,
                "posizioneFinale": 11,
                "giroVeloce": false,
                "pilotaDelGiorno": false,
                "dnf": false,
                "sprint": 13,
            },
            {
                "nome": "Liam Lawson",
                "scuderia": "Red Bull",
                "q1": "1:32.174",
                "q2": "",
                "q3": "",
                "posizioneQualifica": 20,
                "posizioneFinale": 12,
                "giroVeloce": false,
                "pilotaDelGiorno": false,
                "dnf": false,
                "sprint": 14,
            },
            {
                "nome": "Esteban Ocon",
                "scuderia": "Haas",
                "q1": "1:31.876",
                "q2": "1:31.625",
                "q3": "",
                "posizioneQualifica": 11,
                "posizioneFinale": 5,
                "giroVeloce": false,
                "pilotaDelGiorno": false,
                "dnf": false,
                "sprint": 16,
            },
            {
                "nome": "Oliver Bearman",
                "scuderia": "Haas",
                "q1": "1:32.018",
                "q2": "",
                "q3": "",
                "posizioneQualifica": 17,
                "posizioneFinale": 8,
                "giroVeloce": false,
                "pilotaDelGiorno": false,
                "dnf": false,
                "sprint": 15,
            },
            {
                "nome": "Niko Hulkenberg",
                "scuderia": "Sauber",
                "q1": "1:31.921",
                "q2": "1:31.632",
                "q3": "",
                "posizioneQualifica": 12,
                "posizioneFinale": 15,
                "giroVeloce": false,
                "pilotaDelGiorno": false,
                "dnf": false,
                "sprint": 19,
            },
            {
                "nome": "Gabriel Bortoleto",
                "scuderia": "Sauber",
                "q1": "1:32.141",
                "q2": "",
                "q3": "",
                "posizioneQualifica": 19,
                "posizioneFinale": 14,
                "giroVeloce": false,
                "pilotaDelGiorno": false,
                "dnf": false,
                "sprint": 18,
            },
            {
                "nome": "Fernando Alonso",
                "scuderia": "Aston Martin",
                "q1": "1:31.719",
                "q2": "1:31.688",
                "q3": "",
                "posizioneQualifica": 13,
                "posizioneFinale": null,
                "giroVeloce": false,
                "pilotaDelGiorno": false,
                "dnf": true,
                "sprint": 10,
            },
            {
                "nome": "Lance Stroll",
                "scuderia": "Aston Martin",
                "q1": "1:31.923",
                "q2": "1:31.773",
                "q3": "",
                "posizioneQualifica": 14,
                "posizioneFinale": 9,
                "giroVeloce": false,
                "pilotaDelGiorno": false,
                "dnf": false,
                "sprint": 9,
            },
            {
                "nome": "Pierre Gasly",
                "scuderia": "Alpine",
                "q1": "1:31.992",
                "q2": "",
                "q3": "",
                "posizioneQualifica": 16,
                "posizioneFinale": null,
                "giroVeloce": false,
                "pilotaDelGiorno": false,
                "dnf": true,
                "sprint": 12,
            },
            {
                "nome": "Franco Colapinto",
                "scuderia": "Alpine",
                "q1": "1:32.092",
                "q2": "",
                "q3": "",
                "posizioneQualifica": null,
                "posizioneFinale": null,
                "giroVeloce": false,
                "pilotaDelGiorno": false,
                "dnf": false,
                "sprint": null, 
            },
            {
                "nome": "Jack Doohan",
                "scuderia": "Alpine",
                "q1": "1:32.092",
                "q2": "",
                "q3": "",
                "posizioneQualifica": 18,
                "posizioneFinale": 13,
                "giroVeloce": false,
                "pilotaDelGiorno": false,
                "dnf": false,
                "sprint": 20,
            }
        ]
    },
    {
        "anno": 2025,
        "gara": "Giappone",
        "piloti": [
            {
                "nome": "Lando Norris",
                "scuderia": "McLaren",
                "q1": "1:27.845",
                "q2": "1:27.146",
                "q3": "1:26.995",
                "posizioneQualifica": 2,
                "posizioneFinale": 2,
                "giroVeloce": false,
                "pilotaDelGiorno": false,
                "dnf": false
            },
            {
                "nome": "Oscar Piastri",
                "scuderia": "McLaren",
                "q1": "1:27.687",
                "q2": "1:27.507",
                "q3": "1:27.027",
                "posizioneQualifica": 3,
                "posizioneFinale": 3,
                "giroVeloce": false,
                "pilotaDelGiorno": false,
                "dnf": false
            },
            {
                "nome": "Max Verstappen",
                "scuderia": "Red Bull",
                "q1": "1:27.943",
                "q2": "1:27.502",
                "q3": "1:27.983",
                "posizioneQualifica": 1,
                "posizioneFinale": 1,
                "giroVeloce": false,
                "pilotaDelGiorno": false,
                "dnf": false
            },
            {
                "nome": "Yuki Tsunoda",
                "scuderia": "Red Bull",
                "q1": "1:27.967",
                "q2": "1:28.000",
                "q3": "",
                "posizioneQualifica": 15,
                "posizioneFinale": 12,
                "giroVeloce": false,
                "pilotaDelGiorno": true,
                "dnf": false
            },
            {
                "nome": "Charles Leclerc",
                "scuderia": "Ferrari",
                "q1": "1:27.920",
                "q2": "1:27.555",
                "q3": "1:27.299",
                "posizioneQualifica": 4,
                "posizioneFinale": 4,
                "giroVeloce": false,
                "pilotaDelGiorno": false,
                "dnf": false
            },
            {
                "nome": "Lewis Hamilton",
                "scuderia": "Ferrari",
                "q1": "1:27.942",
                "q2": "1:27.610",
                "q3": "1:27.610",
                "posizioneQualifica": 8,
                "posizioneFinale": 7,
                "giroVeloce": false,
                "pilotaDelGiorno": false,
                "dnf": false
            },
            {
                "nome": "George Russell",
                "scuderia": "Mercedes",
                "q1": "1:27.843",
                "q2": "1:27.400",
                "q3": "1:27.318",
                "posizioneQualifica": 5,
                "posizioneFinale": 5,
                "giroVeloce": false,
                "pilotaDelGiorno": false,
                "dnf": false
            },
            {
                "nome": "Kimi Antonelli",
                "scuderia": "Mercedes",
                "q1": "1:27.968",
                "q2": "1:27.639",
                "q3": "1:27.555",
                "posizioneQualifica": 6,
                "posizioneFinale": 6,
                "giroVeloce": true,
                "pilotaDelGiorno": false,
                "dnf": false
            },
            {
                "nome": "Alexander Albon",
                "scuderia": "Williams",
                "q1": "1:28.218",
                "q2": "1:27.783",
                "q3": "1:27.615",
                "posizioneQualifica": 9,
                "posizioneFinale": 9,
                "giroVeloce": false,
                "pilotaDelGiorno": false,
                "dnf": false
            },
            {
                "nome": "Carlos Sainz",
                "scuderia": "Williams",
                "q1": "1:28.209",
                "q2": "1:27.836",
                "q3": "",
                "posizioneQualifica": 12,
                "posizioneFinale": 14,
                "giroVeloce": false,
                "pilotaDelGiorno": false,
                "dnf": false
            },
            {
                "nome": "Isack Hadjar",
                "scuderia": "Racing Bulls",
                "q1": "1:28.278",
                "q2": "1:27.775",
                "q3": "1:27.569",
                "posizioneQualifica": 7,
                "posizioneFinale": 8,
                "giroVeloce": false,
                "pilotaDelGiorno": false,
                "dnf": false
            },
            {
                "nome": "Liam Lawson",
                "scuderia": "Racing Bulls",
                "q1": "1:28.554",
                "q2": "1:27.906",
                "q3": "",
                "posizioneQualifica": 14,
                "posizioneFinale": 17,
                "giroVeloce": false,
                "pilotaDelGiorno": false,
                "dnf": false
            },
            {
                "nome": "Esteban Ocon",
                "scuderia": "Haas",
                "q1": "1:28.696",
                "q2": "",
                "q3": "",
                "posizioneQualifica": 18,
                "posizioneFinale": 18,
                "giroVeloce": false,
                "pilotaDelGiorno": false,
                "dnf": false
            },
            {
                "nome": "Oliver Bearman",
                "scuderia": "Haas",
                "q1": "1:28.2228",
                "q2": "1:27.711",
                "q3": "1:27.867",
                "posizioneQualifica": 10,
                "posizioneFinale": 10,
                "giroVeloce": false,
                "pilotaDelGiorno": false,
                "dnf": false
            },
            {
                "nome": "Niko Hulkenberg",
                "scuderia": "Sauber",
                "q1": "1:28.570",
                "q2": "",
                "q3": "",
                "posizioneQualifica": 16,
                "posizioneFinale": 16,
                "giroVeloce": false,
                "pilotaDelGiorno": false,
                "dnf": false
            },
            {
                "nome": "Gabriel Bortoleto",
                "scuderia": "Sauber",
                "q1": "1:28.622",
                "q2": "",
                "q3": "",
                "posizioneQualifica": 17,
                "posizioneFinale": 19,
                "giroVeloce": false,
                "pilotaDelGiorno": false,
                "dnf": false
            },
            {
                "nome": "Fernando Alonso",
                "scuderia": "Aston Martin",
                "q1": "1:28.337",
                "q2": "1:27.897",
                "q3": "",
                "posizioneQualifica": 13,
                "posizioneFinale": 11,
                "giroVeloce": false,
                "pilotaDelGiorno": false,
                "dnf": false
            },
            {
                "nome": "Lance Stroll",
                "scuderia": "Aston Martin",
                "q1": "1:29.271",
                "q2": "",
                "q3": "",
                "posizioneQualifica": 20,
                "posizioneFinale": 20,
                "giroVeloce": false,
                "pilotaDelGiorno": false,
                "dnf": false
            },
            {
                "nome": "Pierre Gasly",
                "scuderia": "Alpine",
                "q1": "1:28.186",
                "q2": "1:27.822",
                "q3": "",
                "posizioneQualifica": 11,
                "posizioneFinale": 13,
                "giroVeloce": false,
                "pilotaDelGiorno": false,
                "dnf": false
            },
            {
                "nome": "Franco Colapinto",
                "scuderia": "Alpine",
                "q1": "1:28.877",
                "q2": "",
                "q3": "",
                "posizioneQualifica": null,
                "posizioneFinale": null,
                "giroVeloce": false,
                "pilotaDelGiorno": false,
                "dnf": false
            },
            {
                "nome": "Jack Doohan",
                "scuderia": "Alpine",
                "q1": "1:28.877",
                "q2": "",
                "q3": "",
                "posizioneQualifica": 19,
                "posizioneFinale": 15,
                "giroVeloce": false,
                "pilotaDelGiorno": false,
                "dnf": false
            }
        ]
    },
    {
        "anno": 2025,
        "gara": "Bahrain",
        "piloti": [
            {
                "nome": "Lando Norris",
                "scuderia": "McLaren",
                "q1": "1:31.107",
                "q2": "1:30.560",
                "q3": "1:30.267",
                "posizioneQualifica": 6,
                "posizioneFinale": 3,
                "giroVeloce": false,
                "pilotaDelGiorno": false,
                "dnf": false
            },
            {
                "nome": "Oscar Piastri",
                "scuderia": "McLaren",
                "q1": "1:31.392",
                "q2": "1:30.454",
                "q3": "1:29.841",
                "posizioneQualifica": 1,
                "posizioneFinale": 1,
                "giroVeloce": true,
                "pilotaDelGiorno": false,
                "dnf": false
            },
            {
                "nome": "Max Verstappen",
                "scuderia": "Red Bull",
                "q1": "1:31.303",
                "q2": "1:31.019",
                "q3": "1:30.423",
                "posizioneQualifica": 7,
                "posizioneFinale": 6,
                "giroVeloce": false,
                "pilotaDelGiorno": false,
                "dnf": false
            },
            {
                "nome": "Yuki Tsunoda",
                "scuderia": "Red Bull",
                "q1": "1:31.751",
                "q2": "1:31.228",
                "q3": "1:31.303",
                "posizioneQualifica": 10,
                "posizioneFinale": 9,
                "giroVeloce": false,
                "pilotaDelGiorno": false,
                "dnf": false
            },
            {
                "nome": "Charles Leclerc",
                "scuderia": "Ferrari",
                "q1": "1:31.454",
                "q2": "1:30.724",
                "q3": "1:30.175",
                "posizioneQualifica": 3,
                "posizioneFinale": 4,
                "giroVeloce": false,
                "pilotaDelGiorno": false,
                "dnf": false
            },
            {
                "nome": "Lewis Hamilton",
                "scuderia": "Ferrari",
                "q1": "1:31.219",
                "q2": "1:31.009",
                "q3": "1:30.772",
                "posizioneQualifica": 9,
                "posizioneFinale": 5,
                "giroVeloce": false,
                "pilotaDelGiorno": true,
                "dnf": false
            },
            {
                "nome": "George Russell",
                "scuderia": "Mercedes",
                "q1": "1:31.494",
                "q2": "1:30.664",
                "q3": "1:30.009",
                "posizioneQualifica": 2,
                "posizioneFinale": 2,
                "giroVeloce": false,
                "pilotaDelGiorno": false,
                "dnf": false
            },
            {
                "nome": "Kimi Antonelli",
                "scuderia": "Mercedes",
                "q1": "1:31.415",
                "q2": "1:30.716",
                "q3": "1:30.213",
                "posizioneQualifica": 4,
                "posizioneFinale": 11,
                "giroVeloce": false,
                "pilotaDelGiorno": false,
                "dnf": false
            },
            {
                "nome": "Alexander Albon",
                "scuderia": "Williams",
                "q1": "1:32.040",
                "q2": "",
                "q3": "",
                "posizioneQualifica": 15,
                "posizioneFinale": 12,
                "giroVeloce": false,
                "pilotaDelGiorno": false,
                "dnf": false
            },
            {
                "nome": "Carlos Sainz",
                "scuderia": "Williams",
                "q1": "1:31.591",
                "q2": "1:30.844",
                "q3": "1:30.680",
                "posizioneQualifica": 8,
                "posizioneFinale": null,
                "giroVeloce": false,
                "pilotaDelGiorno": false,
                "dnf": true
            },
            {
                "nome": "Isack Hadjar",
                "scuderia": "Racing Bulls",
                "q1": "1:31.591",
                "q2": "1:31.271",
                "q3": "",
                "posizioneQualifica": 12,
                "posizioneFinale": 13,
                "giroVeloce": false,
                "pilotaDelGiorno": false,
                "dnf": false
            },
            {
                "nome": "Liam Lawson",
                "scuderia": "Racing Bulls",
                "q1": "1:32.165",
                "q2": "",
                "q3": "",
                "posizioneQualifica": 17,
                "posizioneFinale": 16,
                "giroVeloce": false,
                "pilotaDelGiorno": false,
                "dnf": false
            },
            {
                "nome": "Esteban Ocon",
                "scuderia": "Haas",
                "q1": "1:31.594",
                "q2": "",
                "q3": "",
                "posizioneQualifica": 14,
                "posizioneFinale": 8,
                "giroVeloce": false,
                "pilotaDelGiorno": false,
                "dnf": false
            },
            {
                "nome": "Oliver Bearman",
                "scuderia": "Haas",
                "q1": "1:32.373",
                "q2": "",
                "q3": "",
                "posizioneQualifica": 20,
                "posizioneFinale": 10,
                "giroVeloce": false,
                "pilotaDelGiorno": false,
                "dnf": false
            },
            {
                "nome": "Niko Hulkenberg",
                "scuderia": "Sauber",
                "q1": "1:32.067",
                "q2": "",
                "q3": "",
                "posizioneQualifica": 16,
                "posizioneFinale": null,
                "giroVeloce": false,
                "pilotaDelGiorno": false,
                "dnf": true
            },
            {
                "nome": "Gabriel Bortoleto",
                "scuderia": "Sauber",
                "q1": "1:32.186",
                "q2": "",
                "q3": "",
                "posizioneQualifica": 18,
                "posizioneFinale": 18,
                "giroVeloce": false,
                "pilotaDelGiorno": false,
                "dnf": false
            },
            {
                "nome": "Fernando Alonso",
                "scuderia": "Aston Martin",
                "q1": "1:31.634",
                "q2": "1:31.886",
                "q3": "",
                "posizioneQualifica": 13,
                "posizioneFinale": 15,
                "giroVeloce": false,
                "pilotaDelGiorno": false,
                "dnf": false
            },
            {
                "nome": "Lance Stroll",
                "scuderia": "Aston Martin",
                "q1": "1:32.283",
                "q2": "",
                "q3": "",
                "posizioneQualifica": 19,
                "posizioneFinale": 17,
                "giroVeloce": false,
                "pilotaDelGiorno": false,
                "dnf": false
            },
            {
                "nome": "Pierre Gasly",
                "scuderia": "Alpine",
                "q1": "1:31.462",
                "q2": "1:30.643",
                "q3": "1:30.216",
                "posizioneQualifica": 5,
                "posizioneFinale": 7,
                "giroVeloce": false,
                "pilotaDelGiorno": false,
                "dnf": false
            },
            {
                "nome": "Franco Colapinto",
                "scuderia": "Alpine",
                "q1": "1:31.462",
                "q2": "",
                "q3": "",
                "posizioneQualifica": null,
                "posizioneFinale": null,
                "giroVeloce": false,
                "pilotaDelGiorno": false,
                "dnf": false
            },
            {
                "nome": "Jack Doohan",
                "scuderia": "Alpine",
                "q1": "1:31.414",
                "q2": "1:31.245",
                "q3": "",
                "posizioneQualifica": 11,
                "posizioneFinale": 14,
                "giroVeloce": false,
                "pilotaDelGiorno": false,
                "dnf": false
            }
        ]
    },
    {
        "anno": 2025,
        "gara": "Arabia Saudita",
        "piloti": [
            {
                "nome": "Lando Norris",
                "scuderia": "McLaren",
                "q1": "1:27.805",
                "q2": "1:27.481",
                "q3": "",
                "posizioneQualifica": 10,
                "posizioneFinale": 4,
                "giroVeloce": true,
                "pilotaDelGiorno": false,
                "dnf": false
            },
            {
                "nome": "Oscar Piastri",
                "scuderia": "McLaren",
                "q1": "1:27.901",
                "q2": "1:27.545",
                "q3": "1:27.304",
                "posizioneQualifica": 2,
                "posizioneFinale": 1,
                "giroVeloce": false,
                "pilotaDelGiorno": false,
                "dnf": false
            },
            {
                "nome": "Max Verstappen",
                "scuderia": "Red Bull",
                "q1": "1:27.778",
                "q2": "1:27.529",
                "q3": "1:27.294",
                "posizioneQualifica": 1,
                "posizioneFinale": 2,
                "giroVeloce": false,
                "pilotaDelGiorno": true,
                "dnf": false
            },
            {
                "nome": "Yuki Tsunoda",
                "scuderia": "Red Bull",
                "q1": "1:28.226",
                "q2": "1:27.990",
                "q3": "1:28.204",
                "posizioneQualifica": 8,
                "posizioneFinale": null,
                "giroVeloce": false,
                "pilotaDelGiorno": false,
                "dnf": true
            },
            {
                "nome": "Charles Leclerc",
                "scuderia": "Ferrari",
                "q1": "1:28.552",
                "q2": "1:27.866",
                "q3": "1:27.670",
                "posizioneQualifica": 4,
                "posizioneFinale": 3,
                "giroVeloce": false,
                "pilotaDelGiorno": false,
                "dnf": false
            },
            {
                "nome": "Lewis Hamilton",
                "scuderia": "Ferrari",
                "q1": "1:28.372",
                "q2": "1:28.102",
                "q3": "1:28.201",
                "posizioneQualifica": 7,
                "posizioneFinale": 7,
                "giroVeloce": false,
                "pilotaDelGiorno": false,
                "dnf": false
            },
            {
                "nome": "George Russell",
                "scuderia": "Mercedes",
                "q1": "1:28.282",
                "q2": "1:27.599",
                "q3": "1:27.407",
                "posizioneQualifica": 3,
                "posizioneFinale": 5,
                "giroVeloce": false,
                "pilotaDelGiorno": false,
                "dnf": false
            },
            {
                "nome": "Kimi Antonelli",
                "scuderia": "Mercedes",
                "q1": "1:28.128",
                "q2": "1:27.798",
                "q3": "1:27.866",
                "posizioneQualifica": 5,
                "posizioneFinale": 6,
                "giroVeloce": false,
                "pilotaDelGiorno": false,
                "dnf": false
            },
            {
                "nome": "Alexander Albon",
                "scuderia": "Williams",
                "q1": "1:28.279",
                "q2": "1:28.109",
                "q3": "",
                "posizioneQualifica": 11,
                "posizioneFinale": 9,
                "giroVeloce": false,
                "pilotaDelGiorno": false,
                "dnf": false
            },
            {
                "nome": "Carlos Sainz",
                "scuderia": "Williams",
                "q1": "1:28.354",
                "q2": "1:28.024",
                "q3": "1:28.164",
                "posizioneQualifica": 6,
                "posizioneFinale": 8,
                "giroVeloce": false,
                "pilotaDelGiorno": false,
                "dnf": false
            },
            {
                "nome": "Isack Hadjar",
                "scuderia": "Racing Bulls",
                "q1": "1:28.571",
                "q2": "1:28.418",
                "q3": "",
                "posizioneQualifica": 14,
                "posizioneFinale": 10,
                "giroVeloce": false,
                "pilotaDelGiorno": false,
                "dnf": false
            },
            {
                "nome": "Liam Lawson",
                "scuderia": "Racing Bulls",
                "q1": "1:28.561",
                "q2": "1:28.191",
                "q3": "",
                "posizioneQualifica": 12,
                "posizioneFinale": 12,
                "giroVeloce": false,
                "pilotaDelGiorno": false,
                "dnf": false
            },
            {
                "nome": "Esteban Ocon",
                "scuderia": "Haas",
                "q1": "1:29.092",
                "q2": "",
                "q3": "",
                "posizioneQualifica": 19,
                "posizioneFinale": 14,
                "giroVeloce": false,
                "pilotaDelGiorno": false,
                "dnf": false
            },
            {
                "nome": "Oliver Bearman",
                "scuderia": "Haas",
                "q1": "1:28.536",
                "q2": "1:28.648",
                "q3": "",
                "posizioneQualifica": 15,
                "posizioneFinale": 13,
                "giroVeloce": false,
                "pilotaDelGiorno": false,
                "dnf": false
            },
            {
                "nome": "Niko Hulkenberg",
                "scuderia": "Sauber",
                "q1": "1:28.782",
                "q2": "",
                "q3": "",
                "posizioneQualifica": 18,
                "posizioneFinale": 15,
                "giroVeloce": false,
                "pilotaDelGiorno": false,
                "dnf": false
            },
            {
                "nome": "Gabriel Bortoleto",
                "scuderia": "Sauber",
                "q1": "1:29.462",
                "q2": "",
                "q3": "",
                "posizioneQualifica": 20,
                "posizioneFinale": 18,
                "giroVeloce": false,
                "pilotaDelGiorno": false,
                "dnf": false
            },
            {
                "nome": "Fernando Alonso",
                "scuderia": "Aston Martin",
                "q1": "1:28.548",
                "q2": "1:28.303",
                "q3": "",
                "posizioneQualifica": 13,
                "posizioneFinale": 11,
                "giroVeloce": false,
                "pilotaDelGiorno": false,
                "dnf": false
            },
            {
                "nome": "Lance Stroll",
                "scuderia": "Aston Martin",
                "q1": "1:28.645",
                "q2": "",
                "q3": "",
                "posizioneQualifica": 16,
                "posizioneFinale": 16,
                "giroVeloce": false,
                "pilotaDelGiorno": false,
                "dnf": false
            },
            {
                "nome": "Pierre Gasly",
                "scuderia": "Alpine",
                "q1": "1:28.421",
                "q2": "1:28.025",
                "q3": "1:28.367",
                "posizioneQualifica": 9,
                "posizioneFinale": null,
                "giroVeloce": false,
                "pilotaDelGiorno": false,
                "dnf": true
            },
            {
                "nome": "Franco Colapinto",
                "scuderia": "Alpine",
                "q1": "1:28.739",
                "q2": "",
                "q3": "",
                "posizioneQualifica": null,
                "posizioneFinale": null,
                "giroVeloce": false,
                "pilotaDelGiorno": false,
                "dnf": false
            },
            {
                "nome": "Jack Doohan",
                "scuderia": "Alpine",
                "q1": "1:28.739",
                "q2": "",
                "q3": "",
                "posizioneQualifica": 17,
                "posizioneFinale": 17,
                "giroVeloce": false,
                "pilotaDelGiorno": false,
                "dnf": false
            }
        ]
    },
    {
        "anno": 2025,
        "gara": "Miami",
        "piloti": [
            {
                "nome": "Lando Norris",
                "scuderia": "McLaren",
                "q1": "1:26.955",
                "q2": "1:26.499",
                "q3": "1:26.269",
                "posizioneQualifica": 2,
                "posizioneFinale": 2,
                "giroVeloce": true,
                "pilotaDelGiorno": false,
                "dnf": false,
                "sprint": 1
            },
            {
                "nome": "Oscar Piastri",
                "scuderia": "McLaren",
                "q1": "1:27.006",
                "q2": "1:26.269",
                "q3": "1:26.375",
                "posizioneQualifica": 4,
                "posizioneFinale": 1,
                "giroVeloce": false,
                "pilotaDelGiorno": true,
                "dnf": false,
                "sprint": 2
            },
            {
                "nome": "Max Verstappen",
                "scuderia": "Red Bull",
                "q1": "1:26.870",
                "q2": "1:26.643",
                "q3": "1:26.204",
                "posizioneQualifica": 1,
                "posizioneFinale": 4,
                "giroVeloce": false,
                "pilotaDelGiorno": false,
                "dnf": false
            },
            {
                "nome": "Yuki Tsunoda",
                "scuderia": "Red Bull",
                "q1": "1:27.298",
                "q2": "1:26.959",
                "q3": "1:26.943",
                "posizioneQualifica": 10,
                "posizioneFinale": 10,
                "giroVeloce": false,
                "pilotaDelGiorno": false,
                "dnf": false,
                "sprint": 6
            },
            {
                "nome": "Charles Leclerc",
                "scuderia": "Ferrari",
                "q1": "1:27.417",
                "q2": "1:26.948",
                "q3": "1:26.754",
                "posizioneQualifica": 8,
                "posizioneFinale": 7,
                "giroVeloce": false,
                "pilotaDelGiorno": false,
                "dnf": false
            },
            {
                "nome": "Lewis Hamilton",
                "scuderia": "Ferrari",
                "q1": "1:27.279",
                "q2": "1:27.006",
                "q3": "",
                "posizioneQualifica": 12,
                "posizioneFinale": 8,
                "giroVeloce": false,
                "pilotaDelGiorno": false,
                "dnf": false,
                "sprint": 3
            },
            {
                "nome": "George Russell",
                "scuderia": "Mercedes",
                "q1": "1:27.014",
                "q2": "1:26.575",
                "q3": "1:26.385",
                "posizioneQualifica": 5,
                "posizioneFinale": 3,
                "giroVeloce": false,
                "pilotaDelGiorno": false,
                "dnf": false,
                "sprint": 4
            },
            {
                "nome": "Kimi Antonelli",
                "scuderia": "Mercedes",
                "q1": "1:27.077",
                "q2": "1:26.606",
                "q3": "1:26.271",
                "posizioneQualifica": 3,
                "posizioneFinale": 6,
                "giroVeloce": false,
                "pilotaDelGiorno": false,
                "dnf": false,
                "sprint": 7
            },
            {
                "nome": "Alexander Albon",
                "scuderia": "Williams",
                "q1": "1:27.042",
                "q2": "1:26.855",
                "q3": "1:26.682",
                "posizioneQualifica": 7,
                "posizioneFinale": 5,
                "giroVeloce": false,
                "pilotaDelGiorno": false,
                "dnf": false
            },
            {
                "nome": "Carlos Sainz",
                "scuderia": "Williams",
                "q1": "1:27.098",
                "q2": "1:26.847",
                "q3": "1:26.569",
                "posizioneQualifica": 6,
                "posizioneFinale": 9,
                "giroVeloce": false,
                "pilotaDelGiorno": false,
                "dnf": false
            },
            {
                "nome": "Isack Hadjar",
                "scuderia": "Racing Bulls",
                "q1": "1:27.301",
                "q2": "1:26.987",
                "q3": "",
                "posizioneQualifica": 11,
                "posizioneFinale": 11,
                "giroVeloce": false,
                "pilotaDelGiorno": false,
                "dnf": false
            },
            {
                "nome": "Liam Lawson",
                "scuderia": "Racing Bulls",
                "q1": "1:27.444",
                "q2": "1:27.363",
                "q3": "",
                "posizioneQualifica": 15,
                "posizioneFinale": null,
                "giroVeloce": false,
                "pilotaDelGiorno": false,
                "dnf": true
            },
            {
                "nome": "Esteban Ocon",
                "scuderia": "Haas",
                "q1": "1:27.450",
                "q2": "1:26.967",
                "q3": "1:26.824",
                "posizioneQualifica": 9,
                "posizioneFinale": 12,
                "giroVeloce": false,
                "pilotaDelGiorno": false,
                "dnf": false
            },
            {
                "nome": "Oliver Bearman",
                "scuderia": "Haas",
                "q1": "1:27.999",
                "q2": "",
                "q3": "",
                "posizioneQualifica": 20,
                "posizioneFinale": null,
                "giroVeloce": false,
                "pilotaDelGiorno": false,
                "dnf": true
            },
            {
                "nome": "Niko Hulkenberg",
                "scuderia": "Sauber",
                "q1": "1:27.473",
                "q2": "",
                "q3": "",
                "posizioneQualifica": 16,
                "posizioneFinale": 14,
                "giroVeloce": false,
                "pilotaDelGiorno": false,
                "dnf": false
            },
            {
                "nome": "Gabriel Bortoleto",
                "scuderia": "Sauber",
                "q1": "1:27.343",
                "q2": "1:27.151",
                "q3": "",
                "posizioneQualifica": 13,
                "posizioneFinale": null,
                "giroVeloce": false,
                "pilotaDelGiorno": false,
                "dnf": true
            },
            {
                "nome": "Fernando Alonso",
                "scuderia": "Aston Martin",
                "q1": "1:27.604",
                "q2": "",
                "q3": "",
                "posizioneQualifica": 17,
                "posizioneFinale": 15,
                "giroVeloce": false,
                "pilotaDelGiorno": false,
                "dnf": false
            },
            {
                "nome": "Lance Stroll",
                "scuderia": "Aston Martin",
                "q1": "1:27.830",
                "q2": "",
                "q3": "",
                "posizioneQualifica": 19,
                "posizioneFinale": 16,
                "giroVeloce": false,
                "pilotaDelGiorno": false,
                "dnf": false,
                "sprint": 5
            },
            {
                "nome": "Pierre Gasly",
                "scuderia": "Alpine",
                "q1": "1:27.710",
                "q2": "",
                "q3": "",
                "posizioneQualifica": 18,
                "posizioneFinale": 13,
                "giroVeloce": false,
                "pilotaDelGiorno": false,
                "dnf": false,
                "sprint": 8
            },
            {
                "nome": "Franco Colapinto",
                "scuderia": "Alpine",
                "q1": "1:27.710",
                "q2": "",
                "q3": "",
                "posizioneQualifica": null,
                "posizioneFinale": null,
                "giroVeloce": false,
                "pilotaDelGiorno": false,
                "dnf": false
            },
            {
                "nome": "Jack Doohan",
                "scuderia": "Alpine",
                "q1": "1:27.422",
                "q2": "1:27.186",
                "q3": "",
                "posizioneQualifica": 14,
                "posizioneFinale": null,
                "giroVeloce": false,
                "pilotaDelGiorno": false,
                "dnf": true
            }
        ]
    },
    {
        "anno": 2025,
        "gara": "Emilia Romagna",
        "piloti": [
            {
                "nome": "Lando Norris",
                "scuderia": "McLaren",
                "q1": "1:15.894",
                "q2": "1:15.261",
                "q3": "1:14.962",
                "posizioneQualifica": 4,
                "posizioneFinale": 2,
                "giroVeloce": false,
                "pilotaDelGiorno": false,
                "dnf": false
            },
            {
                "nome": "Oscar Piastri",
                "scuderia": "McLaren",
                "q1": "1:15.500",
                "q2": "1:15.214",
                "q3": "1:14.670",
                "posizioneQualifica": 1,
                "posizioneFinale": 3,
                "giroVeloce": false,
                "pilotaDelGiorno": false,
                "dnf": false
            },
            {
                "nome": "Max Verstappen",
                "scuderia": "Red Bull",
                "q1": "1:15.175",
                "q2": "1:15.394",
                "q3": "1:14.704",
                "posizioneQualifica": 2,
                "posizioneFinale": 1,
                "giroVeloce": true,
                "pilotaDelGiorno": true,
                "dnf": false
            },
            {
                "nome": "Yuki Tsunoda",
                "scuderia": "Red Bull",
                "q1": "1:16.918",
                "q2": "",
                "q3": "",
                "posizioneQualifica": null,
                "posizioneFinale": 10,
                "giroVeloce": false,
                "pilotaDelGiorno": false,
                "dnf": false
            },
            {
                "nome": "Charles Leclerc",
                "scuderia": "Ferrari",
                "q1": "1:16.108",
                "q2": "1:15.604",
                "q3": "",
                "posizioneQualifica": 11,
                "posizioneFinale": 6,
                "giroVeloce": false,
                "pilotaDelGiorno": false,
                "dnf": false
            },
            {
                "nome": "Lewis Hamilton",
                "scuderia": "Ferrari",
                "q1": "1:16.163",
                "q2": "1:15.765",
                "q3": "",
                "posizioneQualifica": 12,
                "posizioneFinale": 4,
                "giroVeloce": false,
                "pilotaDelGiorno": false,
                "dnf": false
            },
            {
                "nome": "George Russell",
                "scuderia": "Mercedes",
                "q1": "1:15.852",
                "q2": "1:15.334",
                "q3": "1:14.807",
                "posizioneQualifica": 3,
                "posizioneFinale": 7,
                "giroVeloce": false,
                "pilotaDelGiorno": false,
                "dnf": false
            },
            {
                "nome": "Kimi Antonelli",
                "scuderia": "Mercedes",
                "q1": "1:15.943",
                "q2": "1:15.772",
                "q3": "",
                "posizioneQualifica": 13,
                "posizioneFinale": null,
                "giroVeloce": false,
                "pilotaDelGiorno": false,
                "dnf": true
            },
            {
                "nome": "Alexander Albon",
                "scuderia": "Williams",
                "q1": "1:16.123",
                "q2": "1:15.521",
                "q3": "1:15.473",
                "posizioneQualifica": 7,
                "posizioneFinale": 5,
                "giroVeloce": false,
                "pilotaDelGiorno": false,
                "dnf": false
            },
            {
                "nome": "Carlos Sainz",
                "scuderia": "Williams",
                "q1": "1:15.987",
                "q2": "1:15.198",
                "q3": "1:15.432",
                "posizioneQualifica": 6,
                "posizioneFinale": 8,
                "giroVeloce": false,
                "pilotaDelGiorno": false,
                "dnf": false
            },
            {
                "nome": "Isack Hadjar",
                "scuderia": "Racing Bulls",
                "q1": "1:16.253",
                "q2": "1:15.510",
                "q3": "1:15.746",
                "posizioneQualifica": 9,
                "posizioneFinale": 9,
                "giroVeloce": false,
                "pilotaDelGiorno": false,
                "dnf": false
            },
            {
                "nome": "Liam Lawson",
                "scuderia": "Racing Bulls",
                "q1": "1:16.379",
                "q2": "",
                "q3": "",
                "posizioneQualifica": 16,
                "posizioneFinale": 14,
                "giroVeloce": false,
                "pilotaDelGiorno": false,
                "dnf": false
            },
            {
                "nome": "Esteban Ocon",
                "scuderia": "Haas",
                "q1": "1:16.613",
                "q2": "",
                "q3": "",
                "posizioneQualifica": 18,
                "posizioneFinale": null,
                "giroVeloce": false,
                "pilotaDelGiorno": false,
                "dnf": true
            },
            {
                "nome": "Oliver Bearman",
                "scuderia": "Haas",
                "q1": "1:16.918",
                "q2": "",
                "q3": "",
                "posizioneQualifica": 19,
                "posizioneFinale": 17,
                "giroVeloce": false,
                "pilotaDelGiorno": false,
                "dnf": false
            },
            {
                "nome": "Niko Hulkenberg",
                "scuderia": "Sauber",
                "q1": "1:16.518",
                "q2": "",
                "q3": "",
                "posizioneQualifica": 17,
                "posizioneFinale": 12,
                "giroVeloce": false,
                "pilotaDelGiorno": false,
                "dnf": false
            },
            {
                "nome": "Gabriel Bortoleto",
                "scuderia": "Sauber",
                "q1": "1:16.340",
                "q2": "1:16.260",
                "q3": "",
                "posizioneQualifica": 14,
                "posizioneFinale": 18,
                "giroVeloce": false,
                "pilotaDelGiorno": false,
                "dnf": false
            },
            {
                "nome": "Fernando Alonso",
                "scuderia": "Aston Martin",
                "q1": "1:15.695",
                "q2": "1:15..442",
                "q3": "1:15.431",
                "posizioneQualifica": 5,
                "posizioneFinale": 11,
                "giroVeloce": false,
                "pilotaDelGiorno": false,
                "dnf": false
            },
            {
                "nome": "Lance Stroll",
                "scuderia": "Aston Martin",
                "q1": "1:15.817",
                "q2": "1:15.497",
                "q3": "1:15.581",
                "posizioneQualifica": 8,
                "posizioneFinale": 15,
                "giroVeloce": false,
                "pilotaDelGiorno": false,
                "dnf": false
            },
            {
                "nome": "Pierre Gasly",
                "scuderia": "Alpine",
                "q1": "1:15.937",
                "q2": "1:15.505",
                "q3": "1:15.787",
                "posizioneQualifica": 10,
                "posizioneFinale": 13,
                "giroVeloce": false,
                "pilotaDelGiorno": false,
                "dnf": false
            },
            {
                "nome": "Franco Colapinto",
                "scuderia": "Alpine",
                "q1": "1:16.256",
                "q2": "",
                "q3": "",
                "posizioneQualifica": 15,
                "posizioneFinale": 16,
                "giroVeloce": false,
                "pilotaDelGiorno": false,
                "dnf": false
            },
            {
                "nome": "Jack Doohan",
                "scuderia": "Alpine",
                "q1": "1:16.256",
                "q2": "",
                "q3": "",
                "posizioneQualifica": null,
                "posizioneFinale": null,
                "giroVeloce": false,
                "pilotaDelGiorno": false,
                "dnf": false
            }
        ]
    },
    {
        "anno": 2025,
        "gara": "Monaco",
        "piloti": [
            {
                "nome": "Lando Norris",
                "scuderia": "McLaren",
                "q1": "1:11.285",
                "q2": "1:10.570",
                "q3": "1:09.954",
                "posizioneQualifica": 1,
                "posizioneFinale": 1,
                "giroVeloce": true,
                "pilotaDelGiorno": false,
                "dnf": false
            },
            {
                "nome": "Oscar Piastri",
                "scuderia": "McLaren",
                "q1": "1:11.308",
                "q2": "1:10.858",
                "q3": "1:10.129",
                "posizioneQualifica": 3,
                "posizioneFinale": 3,
                "giroVeloce": false,
                "pilotaDelGiorno": false,
                "dnf": false
            },
            {
                "nome": "Max Verstappen",
                "scuderia": "Red Bull",
                "q1": "1:11.431",
                "q2": "1:10.875",
                "q3": "1:10.669",
                "posizioneQualifica": 5,
                "posizioneFinale": 4,
                "giroVeloce": false,
                "pilotaDelGiorno": false,
                "dnf": false
            },
            {
                "nome": "Yuki Tsunoda",
                "scuderia": "Red Bull",
                "q1": "1:11.800",
                "q2": "1:11.415",
                "q3": "",
                "posizioneQualifica": 12,
                "posizioneFinale": 17,
                "giroVeloce": false,
                "pilotaDelGiorno": false,
                "dnf": false
            },
            {
                "nome": "Charles Leclerc",
                "scuderia": "Ferrari",
                "q1": "1:11.229",
                "q2": "1:10.581",
                "q3": "1:10.063",
                "posizioneQualifica": 2,
                "posizioneFinale": 2,
                "giroVeloce": false,
                "pilotaDelGiorno": true,
                "dnf": false
            },
            {
                "nome": "Lewis Hamilton",
                "scuderia": "Ferrari",
                "q1": "1:11.575",
                "q2": "1:10.883",
                "q3": "1:10.382",
                "posizioneQualifica": 4,
                "posizioneFinale": 5,
                "giroVeloce": false,
                "pilotaDelGiorno": false,
                "dnf": false
            },
            {
                "nome": "George Russell",
                "scuderia": "Mercedes",
                "q1": "1:11.507",
                "q2": "",
                "q3": "",
                "posizioneQualifica": 14,
                "posizioneFinale": 11,
                "giroVeloce": false,
                "pilotaDelGiorno": false,
                "dnf": false
            },
            {
                "nome": "Kimi Antonelli",
                "scuderia": "Mercedes",
                "q1": "1:11.880",
                "q2": "",
                "q3": "",
                "posizioneQualifica": 15,
                "posizioneFinale": 18,
                "giroVeloce": false,
                "pilotaDelGiorno": false,
                "dnf": false
            },
            {
                "nome": "Alexander Albon",
                "scuderia": "Williams",
                "q1": "1:11.629",
                "q2": "1:10.732",
                "q3": "1:11.213",
                "posizioneQualifica": 10,
                "posizioneFinale": 9,
                "giroVeloce": false,
                "pilotaDelGiorno": false,
                "dnf": false
            },
            {
                "nome": "Carlos Sainz",
                "scuderia": "Williams",
                "q1": "1:11.707",
                "q2": "1:11.362",
                "q3": "",
                "posizioneQualifica": 11,
                "posizioneFinale": 10,
                "giroVeloce": false,
                "pilotaDelGiorno": false,
                "dnf": false
            },
            {
                "nome": "Isack Hadjar",
                "scuderia": "Racing Bulls",
                "q1": "1:11.811",
                "q2": "1:11.040",
                "q3": "1:10.923",
                "posizioneQualifica": 6,
                "posizioneFinale": 6,
                "giroVeloce": false,
                "pilotaDelGiorno": false,
                "dnf": false
            },
            {
                "nome": "Liam Lawson",
                "scuderia": "Racing Bulls",
                "q1": "1:11.818",
                "q2": "1:11.250",
                "q3": "1:11.129",
                "posizioneQualifica": 9,
                "posizioneFinale": 8,
                "giroVeloce": false,
                "pilotaDelGiorno": false,
                "dnf": false
            },
            {
                "nome": "Esteban Ocon",
                "scuderia": "Haas",
                "q1": "1:11.839",
                "q2": "1:11.262",
                "q3": "1:10.942",
                "posizioneQualifica": 8,
                "posizioneFinale": 7,
                "giroVeloce": false,
                "pilotaDelGiorno": false,
                "dnf": false
            },
            {
                "nome": "Oliver Bearman",
                "scuderia": "Haas",
                "q1": "1:11.979",
                "q2": "",
                "q3": "",
                "posizioneQualifica": 17,
                "posizioneFinale": 12,
                "giroVeloce": false,
                "pilotaDelGiorno": false,
                "dnf": false
            },
            {
                "nome": "Niko Hulkenberg",
                "scuderia": "Sauber",
                "q1": "1:11.871",
                "q2": "1:11.596",
                "q3": "",
                "posizioneQualifica": 13,
                "posizioneFinale": 16,
                "giroVeloce": false,
                "pilotaDelGiorno": false,
                "dnf": false
            },
            {
                "nome": "Gabriel Bortoleto",
                "scuderia": "Sauber",
                "q1": "1:11.902",
                "q2": "",
                "q3": "",
                "posizioneQualifica": 16,
                "posizioneFinale": 14,
                "giroVeloce": false,
                "pilotaDelGiorno": false,
                "dnf": false
            },
            {
                "nome": "Fernando Alonso",
                "scuderia": "Aston Martin",
                "q1": "1:11.674",
                "q2": "1:11.182",
                "q3": "1:10.924",
                "posizioneQualifica": 7,
                "posizioneFinale": null,
                "giroVeloce": false,
                "pilotaDelGiorno": false,
                "dnf": true
            },
            {
                "nome": "Lance Stroll",
                "scuderia": "Aston Martin",
                "q1": "1:12.563",
                "q2": "",
                "q3": "",
                "posizioneQualifica": 19,
                "posizioneFinale": 15,
                "giroVeloce": false,
                "pilotaDelGiorno": false,
                "dnf": false
            },
            {
                "nome": "Pierre Gasly",
                "scuderia": "Alpine",
                "q1": "1:11.994",
                "q2": "",
                "q3": "",
                "posizioneQualifica": 18,
                "posizioneFinale": null,
                "giroVeloce": false,
                "pilotaDelGiorno": false,
                "dnf": true
            },
            {
                "nome": "Franco Colapinto",
                "scuderia": "Alpine",
                "q1": "1:12.597",
                "q2": "",
                "q3": "",
                "posizioneQualifica": 20,
                "posizioneFinale": 13,
                "giroVeloce": false,
                "pilotaDelGiorno": false,
                "dnf": false
            },
            {
                "nome": "Jack Doohan",
                "scuderia": "Alpine",
                "q1": "1:12.597",
                "q2": "",
                "q3": "",
                "posizioneQualifica": null,
                "posizioneFinale": null,
                "giroVeloce": false,
                "pilotaDelGiorno": false,
                "dnf": false
            }
        ]
    },
    {
        "anno": 2025,
        "gara": "Spagna",
        "piloti": [
            {
                "nome": "Lando Norris",
                "scuderia": "McLaren",
                "q1": "1:12.799",
                "q2": "1:12.056",
                "q3": "1:11.755",
                "posizioneQualifica": 2,
                "posizioneFinale": 2,
                "giroVeloce": false,
                "pilotaDelGiorno": false,
                "dnf": false
            },
            {
                "nome": "Oscar Piastri",
                "scuderia": "McLaren",
                "q1": "1:12.551",
                "q2": "1:11.998",
                "q3": "1:11.546",
                "posizioneQualifica": 1,
                "posizioneFinale": 1,
                "giroVeloce": true,
                "pilotaDelGiorno": false,
                "dnf": false
            },
            {
                "nome": "Max Verstappen",
                "scuderia": "Red Bull",
                "q1": "1:12.798",
                "q2": "1:12.358",
                "q3": "1:11.848",
                "posizioneQualifica": 3,
                "posizioneFinale": 10,
                "giroVeloce": false,
                "pilotaDelGiorno": true,
                "dnf": false
            },
            {
                "nome": "Yuki Tsunoda",
                "scuderia": "Red Bull",
                "q1": "1:13.385",
                "q2": "",
                "q3": "",
                "posizioneQualifica": 20,
                "posizioneFinale": 13,
                "giroVeloce": false,
                "pilotaDelGiorno": false,
                "dnf": false
            },
            {
                "nome": "Charles Leclerc",
                "scuderia": "Ferrari",
                "q1": "1:13.014",
                "q2": "1:12.495",
                "q3": "1:12.131",
                "posizioneQualifica": 7,
                "posizioneFinale": 3,
                "giroVeloce": false,
                "pilotaDelGiorno": false,
                "dnf": false
            },
            {
                "nome": "Lewis Hamilton",
                "scuderia": "Ferrari",
                "q1": "1:13.058",
                "q2": "1:12.447",
                "q3": "1:12.045",
                "posizioneQualifica": 5,
                "posizioneFinale": 6,
                "giroVeloce": false,
                "pilotaDelGiorno": false,
                "dnf": false
            },
            {
                "nome": "George Russell",
                "scuderia": "Mercedes",
                "q1": "1:12.806",
                "q2": "1:12.407",
                "q3": "1:11.848",
                "posizioneQualifica": 4,
                "posizioneFinale": 4,
                "giroVeloce": false,
                "pilotaDelGiorno": false,
                "dnf": false
            },
            {
                "nome": "Kimi Antonelli",
                "scuderia": "Mercedes",
                "q1": "1:12.815",
                "q2": "1:12.858",
                "q3": "1:12.111",
                "posizioneQualifica": 6,
                "posizioneFinale": null,
                "giroVeloce": false,
                "pilotaDelGiorno": false,
                "dnf": true
            },
            {
                "nome": "Alexander Albon",
                "scuderia": "Williams",
                "q1": "1:13.044",
                "q2": "1:12.641",
                "q3": "",
                "posizioneQualifica": 11,
                "posizioneFinale": null,
                "giroVeloce": false,
                "pilotaDelGiorno": false,
                "dnf": true
            },
            {
                "nome": "Carlos Sainz",
                "scuderia": "Williams",
                "q1": "1:13.203",
                "q2": "",
                "q3": "",
                "posizioneQualifica": 18,
                "posizioneFinale": 14,
                "giroVeloce": false,
                "pilotaDelGiorno": false,
                "dnf": false
            },
            {
                "nome": "Isack Hadjar",
                "scuderia": "Racing Bulls",
                "q1": "1:13.139",
                "q2": "1:12.461",
                "q3": "1:12.252",
                "posizioneQualifica": 9,
                "posizioneFinale": 7,
                "giroVeloce": false,
                "pilotaDelGiorno": false,
                "dnf": false
            },
            {
                "nome": "Liam Lawson",
                "scuderia": "Racing Bulls",
                "q1": "1:13.039",
                "q2": "1:12.763",
                "q3": "",
                "posizioneQualifica": 13,
                "posizioneFinale": 11,
                "giroVeloce": false,
                "pilotaDelGiorno": false,
                "dnf": false
            },
            {
                "nome": "Esteban Ocon",
                "scuderia": "Haas",
                "q1": "1:13.201",
                "q2": "",
                "q3": "",
                "posizioneQualifica": 17,
                "posizioneFinale": 16,
                "giroVeloce": false,
                "pilotaDelGiorno": false,
                "dnf": false
            },
            {
                "nome": "Oliver Bearman",
                "scuderia": "Haas",
                "q1": "1:13.074",
                "q2": "1:13.315",
                "q3": "",
                "posizioneQualifica": 15,
                "posizioneFinale": 17,
                "giroVeloce": false,
                "pilotaDelGiorno": false,
                "dnf": false
            },
            {
                "nome": "Niko Hulkenberg",
                "scuderia": "Sauber",
                "q1": "1:13.190",
                "q2": "",
                "q3": "",
                "posizioneQualifica": 16,
                "posizioneFinale": 5,
                "giroVeloce": false,
                "pilotaDelGiorno": false,
                "dnf": false
            },
            {
                "nome": "Gabriel Bortoleto",
                "scuderia": "Sauber",
                "q1": "1:13.045",
                "q2": "1:12.756",
                "q3": "",
                "posizioneQualifica": 12,
                "posizioneFinale": 12,
                "giroVeloce": false,
                "pilotaDelGiorno": false,
                "dnf": false
            },
            {
                "nome": "Fernando Alonso",
                "scuderia": "Aston Martin",
                "q1": "1:13.102",
                "q2": "1:12.523",
                "q3": "1:12.284",
                "posizioneQualifica": 10,
                "posizioneFinale": 9,
                "giroVeloce": false,
                "pilotaDelGiorno": false,
                "dnf": false
            },
            {
                "nome": "Lance Stroll",
                "scuderia": "Aston Martin",
                "q1": "1:13.038",
                "q2": "1:13.058",
                "q3": "",
                "posizioneQualifica": 14,
                "posizioneFinale": null,
                "giroVeloce": false,
                "pilotaDelGiorno": false,
                "dnf": false
            },
            {
                "nome": "Pierre Gasly",
                "scuderia": "Alpine",
                "q1": "1:13.081",
                "q2": "1:12.611",
                "q3": "1:12.199",
                "posizioneQualifica": 8,
                "posizioneFinale": 8,
                "giroVeloce": false,
                "pilotaDelGiorno": false,
                "dnf": false
            },
            {
                "nome": "Franco Colapinto",
                "scuderia": "Alpine",
                "q1": "1:13.334",
                "q2": "",
                "q3": "",
                "posizioneQualifica": 19,
                "posizioneFinale": 15,
                "giroVeloce": false,
                "pilotaDelGiorno": false,
                "dnf": false
            },
            {
                "nome": "Jack Doohan",
                "scuderia": "Alpine",
                "q1": "1:13.334",
                "q2": "",
                "q3": "",
                "posizioneQualifica": null,
                "posizioneFinale": null,
                "giroVeloce": false,
                "pilotaDelGiorno": false,
                "dnf": false
            }
        ]
    },
{
  "anno": 2025,
  "gara": "Canada",
  "piloti": [
    {
      "nome": "Lando Norris",
      "scuderia": "McLaren",
      "q1": "1:11.826",
      "q2": "1:11.599",
      "q3": "1:11.625",
      "posizioneQualifica": 7,
      "posizioneFinale": null,
      "giroVeloce": false,
      "pilotaDelGiorno": false,
      "dnf": true
    },
    {
      "nome": "Oscar Piastri",
      "scuderia": "McLaren",
      "q1": "1:11.939",
      "q2": "1:11.715",
      "q3": "1:11.120",
      "posizioneQualifica": 3,
      "posizioneFinale": 4,
      "giroVeloce": false,
      "pilotaDelGiorno": false,
      "dnf": false
    },
    {
      "nome": "Max Verstappen",
      "scuderia": "Red Bull",
      "q1": "1:12.054",
      "q2": "1:11.638",
      "q3": "1:11.059",
      "posizioneQualifica": 2,
      "posizioneFinale": 2,
      "giroVeloce": false,
      "pilotaDelGiorno": false,
      "dnf": false
    },
    {
      "nome": "Yuki Tsunoda",
      "scuderia": "Red Bull",
      "q1": "1:12.334",
      "q2": "1:12.102",
      "q3": "",
      "posizioneQualifica": 11,
      "posizioneFinale": 12,
      "giroVeloce": false,
      "pilotaDelGiorno": false,
      "dnf": false
    },
    {
      "nome": "Charles Leclerc",
      "scuderia": "Ferrari",
      "q1": "1:12.038",
      "q2": "1:11.626",
      "q3": "1:11.682",
      "posizioneQualifica": 8,
      "posizioneFinale": 5,
      "giroVeloce": false,
      "pilotaDelGiorno": false,
      "dnf": false
    },
    {
      "nome": "Lewis Hamilton",
      "scuderia": "Ferrari",
      "q1": "1:11.952",
      "q2": "1:11.885",
      "q3": "1:11.526",
      "posizioneQualifica": 5,
      "posizioneFinale": 6,
      "giroVeloce": false,
      "pilotaDelGiorno": false,
      "dnf": false
    },
    {
      "nome": "George Russell",
      "scuderia": "Mercedes",
      "q1": "1:12.075",
      "q2": "1:11.570",
      "q3": "1:10.899",
      "posizioneQualifica": 1,
      "posizioneFinale": 1,
      "giroVeloce": true,
      "pilotaDelGiorno": false,
      "dnf": false
    },
    {
      "nome": "Kimi Antonelli",
      "scuderia": "Mercedes",
      "q1": "1:12.279",
      "q2": "1:11.974",
      "q3": "1:11.391",
      "posizioneQualifica": 4,
      "posizioneFinale": 3,
      "giroVeloce": false,
      "pilotaDelGiorno": true,
      "dnf": false
    },
    {
      "nome": "Alexander Albon",
      "scuderia": "Williams",
      "q1": "1:12.090",
      "q2": "1:11.892",
      "q3": "1:11.907",
      "posizioneQualifica": 10,
      "posizioneFinale": null,
      "giroVeloce": false,
      "pilotaDelGiorno": false,
      "dnf": true
    },
    {
      "nome": "Carlos Sainz",
      "scuderia": "Williams",
      "q1": "1:12.398",
      "q2": "",
      "q3": "",
      "posizioneQualifica": 17,
      "posizioneFinale": 10,
      "giroVeloce": false,
      "pilotaDelGiorno": false,
      "dnf": false
    },
    {
      "nome": "Isack Hadjar",
      "scuderia": "Racing Bulls",
      "q1": "1:12.211",
      "q2": "1:12.003",
      "q3": "1:11.867",
      "posizioneQualifica": 9,
      "posizioneFinale": 16,
      "giroVeloce": false,
      "pilotaDelGiorno": false,
      "dnf": false
    },
    {
      "nome": "Liam Lawson",
      "scuderia": "Racing Bulls",
      "q1": "1:12.525",
      "q2": "",
      "q3": "",
      "posizioneQualifica": 19,
      "posizioneFinale": null,
      "giroVeloce": false,
      "pilotaDelGiorno": false,
      "dnf": true
    },
    {
      "nome": "Esteban Ocon",
      "scuderia": "Haas",
      "q1": "1:12.378",
      "q2": "1:12.634",
      "q3": "",
      "posizioneQualifica": 15,
      "posizioneFinale": 9,
      "giroVeloce": false,
      "pilotaDelGiorno": false,
      "dnf": false
    },
    {
      "nome": "Oliver Bearman",
      "scuderia": "Haas",
      "q1": "1:12.306",
      "q2": "1:12.340",
      "q3": "",
      "posizioneQualifica": 14,
      "posizioneFinale": 11,
      "giroVeloce": false,
      "pilotaDelGiorno": false,
      "dnf": false
    },
    {
      "nome": "Niko Hulkenberg",
      "scuderia": "Sauber",
      "q1": "1:12.323",
      "q2": "1:12.183",
      "q3": "",
      "posizioneQualifica": 13,
      "posizioneFinale": 8,
      "giroVeloce": false,
      "pilotaDelGiorno": false,
      "dnf": false
    },
    {
      "nome": "Gabriel Bortoleto",
      "scuderia": "Sauber",
      "q1": "1:12.385",
      "q2": "",
      "q3": "",
      "posizioneQualifica": 16,
      "posizioneFinale": 14,
      "giroVeloce": false,
      "pilotaDelGiorno": false,
      "dnf": false
    },
    {
      "nome": "Fernando Alonso",
      "scuderia": "Aston Martin",
      "q1": "1:12.073",
      "q2": "1:11.805",
      "q3": "1:11.596",
      "posizioneQualifica": 6,
      "posizioneFinale": 7,
      "giroVeloce": false,
      "pilotaDelGiorno": false,
      "dnf": false
    },
    {
      "nome": "Lance Stroll",
      "scuderia": "Aston Martin",
      "q1": "1:12.517",
      "q2": "",
      "q3": "",
      "posizioneQualifica": 18,
      "posizioneFinale": 17,
      "giroVeloce": false,
      "pilotaDelGiorno": false,
      "dnf": false
    },
    {
      "nome": "Pierre Gasly",
      "scuderia": "Alpine",
      "q1": "1:12.667",
      "q2": "",
      "q3": "",
      "posizioneQualifica": 20,
      "posizioneFinale": 15,
      "giroVeloce": false,
      "pilotaDelGiorno": false,
      "dnf": false
    },
    {
      "nome": "Franco Colapinto",
      "scuderia": "Alpine",
      "q1": "1:12.234",
      "q2": "1:12.142",
      "q3": "",
      "posizioneQualifica": 12,
      "posizioneFinale": 13,
      "giroVeloce": false,
      "pilotaDelGiorno": false,
      "dnf": false
    },
    {
      "nome": "Jack Doohan",
      "scuderia": "Alpine",
      "q1": "1:12.667",
      "q2": "",
      "q3": "",
      "posizioneQualifica": null,
      "posizioneFinale": null,
      "giroVeloce": false,
      "pilotaDelGiorno": false,
      "dnf": false
    }
  ]
},

];